### ISSUE TITLE
Incorrect response when a file's name is a prefix of another path

### ISSUE THREAD

**Issue by tonyo** [mattrobenolt/s3autoindex#3]
There's a problem with handling file names that are prefixes of other existing names. Example:

https://storybook.getsentry.net/branches/fix-add-store-metrics/runtime~main.92655b55438f79135d20.bundle.js

...gives a directory listing instead of returning the file response.

It looks like the problem is with having this check here:

https://github.com/mattrobenolt/s3autoindex/blob/09a78efe2c6e460f4622cc91a1c1ba08e59d410f/gs.go#L72-L74

...and then doing 

https://github.com/mattrobenolt/s3autoindex/blob/09a78efe2c6e460f4622cc91a1c1ba08e59d410f/gs.go#L91

We should probably do something like: 
1. Remove the first check
2. Remove `len(folders) == 0` from the second check, because our file name might be a prefix of a directory name
3. Look for an empty string in `keys` in the second check (which would mean that we found an exact match)

On a related note, I believe we should return 404 for the following case:
https://storybook.getsentry.net/branches/ma
Essentially, covering the case when there's no exact match for both file and directory.

**Comment by mattrobenolt** [comment]
Damn.
